# Generated by Django 3.2.9 on 2021-12-02 11:54

import app.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.log')),
                ('image', models.ImageField(upload_to=app.utils.input_path)),
                ('description', models.TextField(blank=True, help_text='what is your image', null=True)),
                ('variable_1', models.SmallIntegerField(help_text='بزرگتر از 50', verbose_name='Min Value')),
                ('variable_2', models.SmallIntegerField(help_text='کوچکتر از 500', verbose_name='Max Value')),
                ('name', models.CharField(max_length=200)),
            ],
            bases=('app.log',),
        ),
    ]
