# Generated by Django 3.2.9 on 2021-12-03 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='description',
        ),
        migrations.RemoveField(
            model_name='input',
            name='name',
        ),
    ]
