# Generated by Django 3.2.9 on 2021-12-07 01:20

import app.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211203_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.log')),
                ('Cimage', models.ImageField(upload_to=app.utils.coutput_path)),
                ('Mimage', models.ImageField(upload_to=app.utils.moutput_path)),
                ('CMimage', models.ImageField(upload_to=app.utils.cmoutput_path)),
                ('variable_1', models.SmallIntegerField(help_text='بزرگتر از 50', verbose_name='Min Value')),
                ('variable_2', models.SmallIntegerField(help_text='کوچکتر از 500', verbose_name='Max Value')),
                ('input_ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input', to='app.input')),
            ],
            bases=('app.log',),
        ),
    ]
