# Generated by Django 3.2.9 on 2021-12-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='variable_1',
        ),
        migrations.RemoveField(
            model_name='output',
            name='variable_2',
        ),
    ]
